name: vehicle
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^2.3.1
  dropdown_button2: ^1.6.1
  firebase_auth: ^3.3.19
  firebase_core: ^1.2.0
  cloud_firestore: ^3.1.17
  fluttertoast: ^8.0.9
  intro_slider: ^3.0.5
  smooth_page_indicator: ^1.0.0+2
  google_maps_flutter: ^2.1.8
  geolocator: ^8.2.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  #google_maps_webservice: ^0.0.16
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.3.0






  #location:
    #git:
     # url: https://github.com/Yczar/flutterlocation.git
      #path: packages/location







flutter:


  uses-material-design: true


  assets:
     - assets/images/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

